services:
    db:
        restart: always
        image: mysql/mysql-server
        container_name: mlflow_db
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - backend

    web:
        restart: always
        build: ./img
        image: mlflow_server
        container_name: mlflow_server
        depends_on:
            - db
        command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0
        networks:
            - proxy-net
            - backend

volumes:
    dbdata:

networks:
  proxy-net:
    external: true
  backend:
    internal: true
